In [2]:
import tensorflow as tf
inputs = [
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
]

print(inputs)
inputs = tf.convert_to_tensor(inputs)
inputs = tf.expand_dims(inputs, axis=[0])
inputs = tf.expand_dims(inputs, axis=[3])
inputs = tf.cast(inputs, dtype=tf.float32)
print(inputs)
hidden_size = 15.0
inputs = tf.keras.layers.Dense(hidden_size)(inputs)
print(inputs)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]
tf.Tensor(
[[[[1.]
   [2.]
   [3.]
   [4.]]

  [[2.]
   [3.]
   [4.]
   [5.]]

  [[3.]
   [4.]
   [5.]
   [6.]]]], shape=(1, 3, 4, 1), dtype=float32)
tf.Tensor(
[[[[-0.12697807  0.37876594  0.17475832  0.09452164  0.36152261
    -0.01183307 -0.3038022  -0.02710348 -0.5685881  -0.37786555
    -0.3383447   0.22691089  0.09257001  0.21378297 -0.45368123]
   [-0.25395614  0.7575319   0.34951663  0.18904328  0.72304523
    -0.02366614 -0.6076044  -0.05420697 -1.1371762  -0.7557311
    -0.6766894   0.45382178  0.18514001  0.42756593 -0.90736246]
   [-0.3809342   1.1362978   0.52427495  0.28356493  1.0845678
    -0.03549922 -0.9114066  -0.08131045 -1.7057643  -1.1335967
    -1.0150341   0.68073267  0.27771002  0.6413489  -1.3610437 ]
   [-0.5079123   1.5150638   0.69903326  0.37808657  1.4460905
    -0.04733229 -1.2152088  -0.10841393 -2.2743523  -1.5114622
    -1.3533788   0.90764356  0.37028003  0.85513186 -1.8147249 ]]

  [[-0.25395614  0.7575319 