In [1]:
import tensorflow as tf
import math

print(tf.__version__)

targets = tf.constant([[[0]],[[0]],[[0]],[[0]]])
predictions = tf.constant([[[-0.0587308519]],[[-0.0584287681]],[[-0.00893893559]],[[0.000727241277]]])
targets = tf.cast(targets, dtype=tf.float32)
predictions = tf.cast(predictions, dtype=tf.float32)
weights = tf.constant([[[1]], [[1]], [[1]], [[1]]], dtype=tf.float32)

print(predictions - targets)
l2_loss = tf.pow(predictions - targets, 2)
print(l2_loss*weights)
rmse = tf.sqrt(tf.reduce_sum(l2_loss * weights) / tf.reduce_sum(weights))

rmse

2.5.0
tf.Tensor(
[[[-0.05873085]]

 [[-0.05842877]]

 [[-0.00893894]]

 [[ 0.00072724]]], shape=(4, 1, 1), dtype=float32)
tf.Tensor(
[[[3.4493129e-03]]

 [[3.4139210e-03]]

 [[7.9904567e-05]]

 [[5.2887987e-07]]], shape=(4, 1, 1), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=0.041664336>